//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaccardSimilarityLibraryTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JaccardSimilarityLibraryTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No victim has come forward. There&apos;s no investigation. And physical evidence? That doesn&apos;t exist either.
        ///But thousands of people are convinced that a paedophilia ring involving people at the highest levels of the Democratic Party is operating out of a Washington pizza restaurant.
        ///The story riveted fringes of Twitter - nearly a million messages were sent last month using the term &quot;pizzagate&quot;.
        ///One man even travelled hundreds of miles to the restaurant with a gun and opened fire, claiming he was there to &quot;se [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Pizzagate1 {
            get {
                return ResourceManager.GetString("Pizzagate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US police have arrested a man wielding an assault rifle who entered a pizza restaurant that was the target of fake news reports it was operating a child abuse ring led by Democratic presidential candidate Hillary Clinton and her top campaign aide.
        ///An unidentified 35-year-old man was being held for questioning after police were called to the Comet Ping Pong restaurant in Washington near the Maryland border, said Aquita Brown, a spokeswoman for the Metropolitan Police Department in the nation’s capital.
        ///Fak [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Pizzagate2 {
            get {
                return ResourceManager.GetString("Pizzagate2", resourceCulture);
            }
        }
    }
}
