//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompareTexts.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CompareTexts.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What follows is shocking evidence that crisis actors, green screens, CGI, and paid propagandists are being used to fake worldwide events in order to scare people into giving up liberties and sending us into war.
        ///
        ///To say this was shocking would be to put it lightly.
        ///From video proof showing “dead soldiers” killed by “chemical weapons” walking around after they thought the videos stopped recording, to digitally altering sounds to add in “explosions” that never happened, this segment demonstrates some of th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _03_11_2016_Higgs_News_Network_BBC_And_CNN_News_Caught_Staging_FAKE_News {
            get {
                return ResourceManager.GetString("_03_11_2016_Higgs_News_Network_BBC_And_CNN_News_Caught_Staging_FAKE_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Wednesday the Bishop Of Rome addressed 11,000 ticketed guests on the South Lawn of the White House, during which he pontificated on the dire importance of exhibiting religious tolerance. During his hour-long speech, a smiling Pope Francis was quoted telling the White House guests that the Koran, and the spiritual teachings contained therein, are just as valid as the Holy Bible, and should therefore be respected as such.
        ///
        ///&quot;Jesus Christ, Jehovah, Allah. These are all names employed to describe an entity  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _05_03_2017_Koran_Bible_Same1 {
            get {
                return ResourceManager.GetString("_05_03_2017_Koran_Bible_Same1", resourceCulture);
            }
        }
    }
}
