//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompareTextTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CompareTextTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well, that didn’t take long. Just hours after Hillary Clinton lost the presidency to Donald Trump 
        ///— and hours after she left her disconsolate supporters at New York City’s Javits Center, hightailing it to the confines of
        ///Manhattan’s Peninsula Hotel—cries of “sexism” erupted across America’s fruited plain. On Twitter, under the top-trending hashtag 
        ///#NotMyPresident, many Americans bemoaned the “misogyny” that allegedly doomed Clinton from the start. 
        ///“Trump didn’t win because of Comey,” MSNBC’s Jonathan [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _11_11_2016_Nationalreview_Hillary_Clinton {
            get {
                return ResourceManager.GetString("_11_11_2016_Nationalreview_Hillary_Clinton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syria chemical &apos;attack&apos;: What we know
        ///At least 70 people have been killed in a suspected chemical attack on the rebelheld
        ///town of Khan
        ///Sheikhoun in northwestern
        ///Syria.
        ///Hundreds suffered symptoms consistent with reaction to a nerve agent after what the opposition and
        ///Western powers said was a Syrian government air strike on the area on Tuesday morning.
        ///The Syrian military denied using any chemical agents, while its ally Russia said an air strike hit a rebel depot
        ///full of chemical munitions.
        ///What hap [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _20_04_2017_Syria_news_BBC {
            get {
                return ResourceManager.GetString("_20_04_2017_Syria_news_BBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Monday the Bishop Of Rome addressed Catholic followers regarding the dire importance of exhibiting religious tolerance. During his hour-long speech, a smiling Pope Francis was quoted telling the Vatican’s guests that the Koran, and the spiritual teachings contained therein, are just as valid as the Holy Bible.
        ///
        ///“Jesus Christ, Mohammed, Jehovah, Allah. These are all names employed to describe an entity that is distinctly the same across the world. For centuries, blood has been needlessly shed because of [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _24_09_2015_Koran_Bible_Same2 {
            get {
                return ResourceManager.GetString("_24_09_2015_Koran_Bible_Same2", resourceCulture);
            }
        }
    }
}
